version: '3.7'
services:
  rtmp:
    image: alfg/nginx-rtmp
    container_name: rtmp-nginx
    ports:
      - '800:80'
      - '1935:1935'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/tmp
